In [1]:
import torch

In [2]:
# Sigmoid function
def sigmoid(x):
    return 1/(1 + torch.exp(-x))

### SingleLayer Neural Network

In [3]:
# create tensor of normal variables 
torch.manual_seed(7)
x = torch.randn((1,5))

In [4]:
# create another tensor of same shape as tensor x
w = torch.randn_like(x)

In [5]:
# create bias
b = torch.randn((1,1))

In [6]:
# y = acivation(sigma(wx)+b)

#method - 1 element wise multiplication
y = sigmoid(torch.sum(x*w) + b)
print(y)

tensor([[0.1595]])


In [7]:
# Method -2 using libraries for faster multiplication
# Can use both *torch.mm()* or *torch.matmul()* 
# But torch.mm() is more better to use
# we need to modify shape of tensor to make it suitable for matrix multiplication

wShape = w.shape
# print(wShape) -->  torch.Size([1, 5])
wT = w.reshape(5, 1)
print('w', w)
print('wT', wT)

w tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
wT tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])


In [8]:
yNew = sigmoid(torch.mm(x, wT) + b)
print(yNew)

tensor([[0.1595]])


### MultiLayer Neural Network

In [9]:
torch.manual_seed(7)
# Features vector --> input vector 'x'
features = torch.randn((1, 3))

n_input = features.shape[1]
n_hidden = 2
n_output = 1

# weight matrices
W1 = torch.randn(n_input, n_hidden)
W2 = torch.randn(n_hidden, n_output)

#create bias vector

B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [10]:
# y = f2(f1(xW1 + b1)W2 + b2)
h = sigmoid(torch.mm(features, W1) + B1)
y = sigmoid(torch.mm(h, W2) + B2)
print(y)

tensor([[0.3171]])
